import React, { useState, useEffect, useRef } from "react";
import axios from "axios";
import { useAuth } from "../../context/AuthContext";
import { TEST_IDS } from "../../constants/testIds";
import { Users, Search, Phone, MapPin, ShieldAlert, CheckCircle2, XCircle, MessageSquare, Trash2, ExternalLink, Radio, UserMinus, RotateCcw, Archive } from "lucide-react";
import { toast } from "sonner";
import ClientRegistrationWizard from "./usuarios/ClientRegistrationWizard";
import ClientDetail from "./ClientDetail";
import CoordinatesPicker from "../red/components/CoordinatesPicker";
import { showDeleteModal } from "../../constants/clientDeleteGuard";
import "./clients-theme.css";

const emptyForm = (planId = "", routerId = "") => ({
  full_name:"", dni_ruc:"", phone:"", email:"", address:"", reference:"", latitude:"", longitude:"", ip_address:"", onu_sn:"", connection_type:"PPPoE", pppoe_user:"", pppoe_password:"", plan_id:planId, router_id:routerId, ipv4_network_id:"", nap_box:"", nap_box_id:"", nap_port:"", optical_power_dbm:"", installation_date:new Date().toISOString().slice(0,10), technology:"fiber", zone_id:"", zone_name:"", monitoring_equipment_id:"", monitoring_equipment_name:"", antenna_type:"", management_ip:"", status:"active", billing_day:new Date().getDate(), billing_type:"prepaid", invoice_lead_days:5, grace_days:5, cut_after_months:1, invoice_notification_channel:"none", payment_reminder_channel:"none", reminder_1_days:null, reminder_2_days:null, reminder_3_days:null, create_first_invoice:true
});

export default function Clients() {
  const { API, token } = useAuth();
  const headers = { Authorization: `Bearer ${token}` };
  const [clients,setClients]=useState([]), [retired,setRetired]=useState([]), [plans,setPlans]=useState([]), [routers,setRouters]=useState([]), [ipv4Networks,setIpv4Networks]=useState([]), [napBoxes,setNapBoxes]=useState([]);
  const [loading,setLoading]=useState(true), [search,setSearch]=useState(""), [statusFilter,setStatusFilter]=useState("all"), [activeTab,setActiveTab]=useState("clients");
  const [showAddModal,setShowAddModal]=useState(false), [detailClientId,setDetailClientId]=useState(null), [selectedClient,setSelectedClient]=useState(null), [locationClient,setLocationClient]=useState(null), [formData,setFormData]=useState(emptyForm());
  const [retireClient,setRetireClient]=useState(null), [retireReason,setRetireReason]=useState(""), [retiring,setRetiring]=useState(false);
  const installationDraftConsumed=useRef(false);
  const activePlans=plans.filter(p=>p.is_active), mikrotikRouters=routers.filter(r=>r.device_type==="mikrotik");

  const fetchData=async()=>{ setLoading(true); try { const [a,b,c,d,e,f]=await Promise.all([
    axios.get(`${API}/clients`,{params:{search,status:statusFilter},headers}), axios.get(`${API}/clients/retired/list`,{params:{search},headers}), axios.get(`${API}/plans`,{headers}), axios.get(`${API}/routers`,{headers}), axios.get(`${API}/ipv4-networks`,{headers}), axios.get(`${API}/nap-boxes`,{headers})]);
    setClients((Array.isArray(a.data)?a.data:[]).filter(x=>x.status!=="retired")); setRetired(Array.isArray(b.data)?b.data:[]); setPlans(c.data); setRouters(d.data); setIpv4Networks(e.data); setNapBoxes(f.data);
  } catch(e){ console.error(e); toast.error("Error al cargar clientes"); } finally { setLoading(false); }};
  useEffect(()=>{fetchData();},[search,statusFilter]);

  useEffect(()=>{ if(loading||installationDraftConsumed.current)return; installationDraftConsumed.current=true; const raw=sessionStorage.getItem("zhub_installation_draft"); if(!raw)return; try{const draft=JSON.parse(raw);setSelectedClient(null);setFormData({...emptyForm(activePlans[0]?.id||"",mikrotikRouters[0]?.id||""),...draft});setShowAddModal(true);}catch(_){}finally{sessionStorage.removeItem("zhub_installation_draft");}},[loading,plans,routers]);

  const handleSaveClient=async(e)=>{e.preventDefault();const isWireless=formData.technology==="wireless";const payload={...formData,nap_box_id:isWireless?"":formData.nap_box_id,nap_box:isWireless?"":formData.nap_box,nap_port:isWireless||formData.nap_port===""||formData.nap_port==null?null:Number(formData.nap_port),optical_power_dbm:formData.optical_power_dbm===""?null:formData.optical_power_dbm,latitude:formData.latitude===""?0:Number(formData.latitude),longitude:formData.longitude===""?0:Number(formData.longitude),status:"active"};
    try{const wasRetired=selectedClient?.status==="retired";const res=selectedClient?await axios.put(`${API}/clients/${selectedClient.id}`,payload,{headers}):await axios.post(`${API}/clients`,payload,{headers});if(wasRetired)await axios.post(`${API}/clients/${selectedClient.id}/reactivation-complete`,{},{headers});toast.success(wasRetired?"Cliente reactivado y registrado nuevamente":"Cliente guardado correctamente");if(res.data.mikrotik)(res.data.mikrotik.ok?toast.success:toast.warning)(`MikroTik: ${res.data.mikrotik.message}`);setShowAddModal(false);setSelectedClient(null);setActiveTab("clients");fetchData();}catch(e){toast.error(typeof e.response?.data?.detail==="string"?e.response.data.detail:"Error al guardar cliente");}};

  const startReactivation=(c)=>{setSelectedClient(c);setFormData({...emptyForm(activePlans[0]?.id||"",mikrotikRouters[0]?.id||""),full_name:c.full_name,dni_ruc:c.dni_ruc,phone:c.phone,email:c.email,address:c.address,reference:c.reference,latitude:c.latitude||"",longitude:c.longitude||"",technology:c.technology||"fiber",installation_date:new Date().toISOString().slice(0,10),status:"active"});setShowAddModal(true);};
  const confirmRetirement=async()=>{const reason=retireReason.trim();if(reason.length<10)return toast.error("El motivo debe tener al menos 10 caracteres.");if(reason.length>250)return toast.error("El motivo no puede superar 250 caracteres.");setRetiring(true);try{const res=await axios.post(`${API}/clients/${retireClient.id}/retire`,{reason},{headers});toast.success(res.data.message);setRetireClient(null);setRetireReason("");fetchData();}catch(e){toast.error(e.response?.data?.detail||"No se pudo retirar al cliente.");}finally{setRetiring(false);}};
  const toggle=async(c)=>{try{const r=await axios.post(`${API}/clients/${c.id}/toggle-status`,{},{headers});(r.data.mikrotik?.ok?toast.success:toast.warning)(r.data.message);fetchData();}catch(e){toast.error(e.response?.data?.detail||"Error al cambiar estado");}};
  const onu=async(c)=>{try{const r=await axios.get(`${API}/clients/${c.id}/onu-status`,{headers});if(!r.data.found)return toast.warning(r.data.message);toast.success(`${r.data.olt} · PON 0/${r.data.pon} · ONU ${r.data.onu_id}`,{duration:10000});}catch(e){toast.error(e.response?.data?.detail||"No se pudo consultar la OLT");}};
  const whatsapp=(c)=>{const p=(c.phone||"").replace(/\D/g,"");window.open(`https://wa.me/51${p}?text=${encodeURIComponent(`Hola ${c.full_name}, le contactamos desde Z-Hub.`)}`,"_blank");};
  const remove=async(c)=>{try{const [s,i]=await Promise.all([axios.get(`${API}/clients/${c.id}/services`,{headers}),axios.get(`${API}/clients/${c.id}/invoices`,{headers})]);const inv=Array.isArray(i.data)?i.data:[],pending=inv.filter(x=>["unpaid","overdue"].includes(String(x.status||"").toLowerCase())),balance=pending.reduce((t,x)=>t+Math.max(0,Number(x.amount||0)-Number(x.paid_amount||0)),0);if(!await showDeleteModal({clientName:c.full_name,services:Array.isArray(s.data)?s.data:[],pendingCount:pending.length,pendingTotal:balance,priority:true}))return;await axios.delete(`${API}/clients/${c.id}`,{headers,__mikrohubDeleteConfirmed:true});toast.success("Cliente eliminado del sistema");fetchData();}catch(e){toast.error("La eliminación fue cancelada.");}};

  return <div className="clients-page space-y-5 animate-in fade-in duration-200">
    <div className="clients-header rounded-2xl p-4"><h2 className="clients-title flex items-center gap-2 text-2xl font-bold"><Users className="w-6 h-6 text-cyan-400"/> Control de Clientes</h2><p className="clients-subtitle text-xs mt-1">Administración de clientes activos y conservación del historial de clientes retirados.</p>
      <div className="mt-4 flex gap-2"><button onClick={()=>setActiveTab("clients")} className={`px-4 py-2 rounded-xl text-xs font-bold ${activeTab==="clients"?"bg-cyan-500 text-white":"bg-slate-200 text-slate-700"}`}>Clientes ({clients.length})</button><button onClick={()=>setActiveTab("retired")} className={`px-4 py-2 rounded-xl text-xs font-bold ${activeTab==="retired"?"bg-amber-500 text-white":"bg-slate-200 text-slate-700"}`}><Archive className="inline w-4 h-4 mr-1"/> Retirados ({retired.length})</button></div>
    </div>
    <div className="clients-controls bg-slate-900/90 border border-slate-800 rounded-xl p-4 shadow-xl flex flex-col md:flex-row gap-4 items-center justify-between"><div className="relative w-full md:w-96"><Search className="w-4 h-4 text-slate-500 absolute left-3.5 top-3"/><input data-testid={TEST_IDS.CLIENT_SEARCH} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nombre, DNI/RUC, IP, teléfono o dirección..." className="w-full pl-10 pr-4 py-2 bg-slate-950 border border-slate-700 rounded-xl text-xs text-slate-200"/></div>{activeTab==="clients"&&<div className="flex gap-2"><button onClick={()=>setStatusFilter("all")} className="px-3 py-1.5 rounded-lg text-xs bg-cyan-500 text-white">Todos</button><button onClick={()=>setStatusFilter("active")} className="px-3 py-1.5 rounded-lg text-xs bg-emerald-500 text-white">Activos</button><button onClick={()=>setStatusFilter("suspended")} className="px-3 py-1.5 rounded-lg text-xs bg-rose-500 text-white">Suspendidos</button></div>}</div>

    {activeTab==="clients"?<div className="clients-table-card bg-slate-900/90 border border-slate-800 rounded-xl shadow-xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-950 text-slate-400 uppercase"><tr><th className="py-3 px-4">Abonado / Contacto</th><th className="py-3 px-4">Plan / Tarifa</th><th className="py-3 px-4">IP / Conexión</th><th className="py-3 px-4">Estado / Deuda</th><th className="py-3 px-4 text-center">Acciones</th></tr></thead><tbody>{loading?<tr><td colSpan="5" className="p-8 text-center">Cargando...</td></tr>:clients.map(c=><tr key={c.id} className="border-t border-slate-800/60"><td className="py-3 px-4"><b>{c.full_name}</b><div>DNI: {c.dni_ruc} · <Phone className="inline w-3 h-3"/> {c.phone}</div><button onClick={()=>setLocationClient(c)} className="mt-1 px-2 py-1 rounded border"><MapPin className="inline w-3 h-3"/> Ubicación</button></td><td className="py-3 px-4"><b>{c.plan_name}</b><div>S/. {Number(c.plan_price||0).toFixed(2)} / mes</div></td><td className="py-3 px-4"><b>{c.ip_address}</b><div>{c.connection_type}: {c.pppoe_user||"estática"}</div><small>Router: {c.router_name}</small></td><td className="py-3 px-4">{c.status==="active"?<span className="text-emerald-500 font-bold"><CheckCircle2 className="inline w-4 h-4"/> ACTIVO</span>:<span className="text-rose-500 font-bold"><XCircle className="inline w-4 h-4"/> CORTADO</span>}<div>S/. {Number(c.balance_due||0).toFixed(2)}</div></td><td className="py-3 px-4"><div className="flex justify-center gap-1.5"><button onClick={()=>setDetailClientId(c.id)} title="Ver ficha" className="p-1.5 rounded-lg border text-cyan-500"><ExternalLink className="w-4 h-4"/></button><button onClick={()=>toggle(c)} title="Cortar / reactivar servicio" className="p-1.5 rounded-lg border text-rose-500"><ShieldAlert className="w-4 h-4"/></button>{c.onu_sn&&<button onClick={()=>onu(c)} title="Ver ONU" className="p-1.5 rounded-lg border text-cyan-500"><Radio className="w-4 h-4"/></button>}<button onClick={()=>whatsapp(c)} title="WhatsApp" className="p-1.5 rounded-lg border text-emerald-500"><MessageSquare className="w-4 h-4"/></button><button onClick={()=>{setRetireClient(c);setRetireReason("");}} title="Retirar cliente" className="p-1.5 rounded-lg border border-amber-400 bg-amber-50 text-amber-600"><UserMinus className="w-4 h-4"/></button><button onClick={()=>remove(c)} title="Eliminar" className="p-1.5 rounded-lg border text-slate-500"><Trash2 className="w-4 h-4"/></button></div></td></tr>)}</tbody></table></div></div>
    :<div className="rounded-xl border bg-white shadow-xl overflow-hidden"><table className="w-full text-left text-xs"><thead className="bg-slate-100 text-slate-700 uppercase"><tr><th className="p-3">Cliente</th><th className="p-3">Contacto</th><th className="p-3">Dirección</th><th className="p-3">Fecha retiro</th><th className="p-3">Motivo</th><th className="p-3">Acción</th></tr></thead><tbody>{retired.length?retired.map(c=><tr key={c.id} className="border-t"><td className="p-3 font-bold">{c.full_name}<div className="font-normal">DNI/RUC: {c.dni_ruc}</div></td><td className="p-3">{c.phone}<div>{c.email}</div></td><td className="p-3">{c.address}</td><td className="p-3">{(c.retired_at||"").slice(0,10)||"—"}</td><td className="p-3 max-w-sm">{c.retirement_reason}</td><td className="p-3"><button onClick={()=>startReactivation(c)} className="inline-flex items-center gap-2 rounded-lg bg-emerald-500 px-3 py-2 font-bold text-white"><RotateCcw className="w-4 h-4"/> Reactivar / volver a registrar</button></td></tr>):<tr><td colSpan="6" className="p-8 text-center text-slate-500">No hay clientes retirados.</td></tr>}</tbody></table></div>}

    {retireClient&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl text-slate-800"><h3 className="text-xl font-extrabold flex items-center gap-2"><UserMinus className="text-amber-500"/> Retirar cliente</h3><div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm"><b>{retireClient.full_name}</b><div>DNI/RUC: {retireClient.dni_ruc}</div><div>Teléfono: {retireClient.phone}</div><div>Dirección: {retireClient.address}</div><div className="mt-3 font-bold text-amber-700">Se liberará:</div><div>Router/MikroTik, PPPoE/Queue, IP, plan, NAP/puerto, ONU y asociaciones técnicas. El cliente quedará únicamente en el historial de Retirados.</div></div><label className="block mt-4 text-sm font-bold">Motivo del retiro * <span className="font-normal text-slate-500">(10–250 caracteres)</span><textarea value={retireReason} maxLength={250} onChange={e=>setRetireReason(e.target.value)} className="mt-2 w-full min-h-28 rounded-xl border p-3" placeholder="Escribe obligatoriamente el motivo del retiro..."/><div className="text-right text-xs text-slate-500">{retireReason.length}/250</div></label><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setRetireClient(null)} className="rounded-lg border px-4 py-2">Cancelar</button><button disabled={retiring||retireReason.trim().length<10} onClick={confirmRetirement} className="rounded-lg bg-amber-500 px-4 py-2 font-bold text-white disabled:opacity-40">{retiring?"Retirando...":"Confirmar retiro"}</button></div></div></div>}
    {locationClient&&<CoordinatesPicker title={`Ubicación de ${locationClient.full_name}`} latitude={locationClient.latitude} longitude={locationClient.longitude} address={locationClient.address} reference={locationClient.reference} readOnly onClose={()=>setLocationClient(null)}/>} {detailClientId&&<ClientDetail clientId={detailClientId} api={API} token={token} onClose={()=>setDetailClientId(null)} onClientUpdated={fetchData}/>} {showAddModal&&<ClientRegistrationWizard selectedClient={selectedClient} formData={formData} setFormData={setFormData} plans={plans} routers={routers} ipv4Networks={ipv4Networks} napBoxes={napBoxes} onClose={()=>{setShowAddModal(false);setSelectedClient(null);}} onSubmit={handleSaveClient} api={API} token={token}/>} 
  </div>;
}
