/** Opciones de Ajustes: menú lateral y contenido aislado por identificador. */
export const SETTINGS_SECTIONS = [
  { id:"general", label:"General" },
  { id:"staff", label:"Gestión personal" },
  { id:"mail", label:"Servidor de correo" },
  { id:"billing", label:"Facturación" },
  { id:"electronic", label:"Facturación electrónica" },
  { id:"payments", label:"Pasarelas de pago" },
  { id:"templates", label:"Editor plantillas" },
  { id:"portal", label:"Portal cliente" },
  { id:"push", label:"Notificaciones Push" },
  { id:"tickets", label:"Tickets" },
  { id:"zendesk", label:"Zendesk Support" },
  { id:"blacklist", label:"Monitor Blacklist" },
  { id:"import", label:"Importar clientes" },
  { id:"bulk", label:"Cambios masivos" },
  { id:"config_templates", label:"Plantillas configuración" },
  { id:"invoice_messages", label:"Mensajes facturas" },
  { id:"locations", label:"Ubicaciones" },
  { id:"custom_fields", label:"Campos personalizados" },
  { id:"messaging", label:"Mensajería" },
  { id:"cloud", label:"Cloud" },
  { id:"google", label:"Google Maps y APIs" },
  { id:"database", label:"Base de datos" },
  { id:"crontab", label:"Crontab" },
  { id:"logs", label:"Logs" },
  { id:"system", label:"Sistema" },
  { id:"server", label:"Servidor" },
  { id:"migrate", label:"Migrar" },
  { id:"freeradius", label:"FreeRADIUS" },
  { id:"license", label:"Licencia" },
];
