/**
 * Z-Hub — Servicios de Internet del cliente.
 * Modal compacto de alta/edición con flujo progresivo Router → Tecnología → Plan → Conexión → Acceso → Zona.
 */
import React, { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { AlertCircle, CheckCircle2, Loader, Pencil, Plus, Save, Trash2, X } from "lucide-react";
import "./client-service-wizard.css";

const inputClass = "service-wizard-input";
const emptyForm = { plan_id:"", router_id:"", connection_type:"IP Estática", ipv4_network_id:"", ip_address:"", pppoe_user:"", pppoe_password:"", technology:"", zone_id:"", nap_box_id:"", nap_port:"", onu_sn:"", optical_power_dbm:"", monitoring_equipment_id:"", antenna_type:"", management_ip:"" };
const mapServiceToForm = (s) => ({ ...emptyForm, plan_id:s?.plan_id||"", router_id:s?.router_id||"", connection_type:s?.connection_type||"IP Estática", ipv4_network_id:s?.ipv4_network_id||"", ip_address:s?.ip_address||"", pppoe_user:s?.pppoe_user||"", pppoe_password:s?.pppoe_password||"", technology:s?.technology||"", zone_id:s?.zone_id||"", nap_box_id:s?.nap_box_id||"", nap_port:s?.nap_port?String(s.nap_port):"", onu_sn:s?.onu_sn||"", optical_power_dbm:s?.optical_power_dbm??"", monitoring_equipment_id:s?.monitoring_equipment_id||"", antenna_type:s?.antenna_type||"", management_ip:s?.management_ip||"" });
const planTechnology = (type="") => { const v=String(type).toLowerCase(); if(v.includes("hotspot")) return "hotspot"; if(v.includes("radio")||v.includes("inalam")||v.includes("inalám")||v.includes("ubiquiti")||v.includes("mimosa")) return "wireless"; return "fiber"; };
const resetTechnical = { ipv4_network_id:"", ip_address:"", pppoe_user:"", pppoe_password:"", zone_id:"", nap_box_id:"", nap_port:"", onu_sn:"", optical_power_dbm:"", monitoring_equipment_id:"", antenna_type:"", management_ip:"" };

function Field({label,children}) { return <div className="min-w-0"><label className="service-wizard-label mb-1.5 block">{label}</label>{children}</div>; }
function getOpticalPowerTone(value){ const n=Number(value); if(!Number.isFinite(n)||value==="")return"normal"; const d=-Math.abs(n); if(d<=-28)return"critical"; if(d<=-25)return"warning"; return"good"; }
const opticalPowerBadgeClass=(value)=>({critical:"bg-rose-500/15 text-rose-300 ring-1 ring-rose-500/30",warning:"bg-amber-500/15 text-amber-300 ring-1 ring-amber-500/30",good:"bg-emerald-500/15 text-emerald-300 ring-1 ring-emerald-500/20",normal:"bg-slate-800 text-slate-300"}[getOpticalPowerTone(value)]);

function ServiceModal({clientId,api,token,service,onSaved,onClose}) {
  const editingPrimary=service?.is_primary;
  const [formData,setFormData]=useState(()=>service?mapServiceToForm(service):{...emptyForm});
  const [plans,setPlans]=useState([]),[routers,setRouters]=useState([]),[ipv4Networks,setIpv4Networks]=useState([]),[zones,setZones]=useState([]),[napBoxes,setNapBoxes]=useState([]),[monitoringEquipment,setMonitoringEquipment]=useState([]),[availableAddresses,setAvailableAddresses]=useState([]);
  const [loading,setLoading]=useState(true),[loadingAddresses,setLoadingAddresses]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");

  useEffect(()=>{ let active=true;(async()=>{try{const headers={Authorization:`Bearer ${token}`};const [a,b,c,d,e,f]=await Promise.all([axios.get(`${api}/plans`,{headers}),axios.get(`${api}/routers`,{headers}),axios.get(`${api}/ipv4-networks`,{headers}),axios.get(`${api}/zones`,{headers}),axios.get(`${api}/nap-boxes`,{headers}),axios.get(`${api}/monitoring-equipment`,{headers})]);if(!active)return;setPlans(a.data||[]);setRouters((b.data||[]).filter(r=>r.device_type==="mikrotik"));setIpv4Networks(c.data||[]);setZones(d.data||[]);setNapBoxes(e.data||[]);setMonitoringEquipment(f.data||[]);}catch(err){if(active)setError(err.response?.data?.detail||"No se pudieron cargar los datos del servicio.");}finally{if(active)setLoading(false);}})();return()=>{active=false};},[api,token]);

  const compatiblePlans=useMemo(()=>plans.filter(p=>p.is_active!==false&&planTechnology(p.type)===formData.technology),[plans,formData.technology]);
  const usage={PPPoE:"pppoe_pool","IP Estática":"static",DHCP:"dhcp"}[formData.connection_type]||"static";
  const compatibleNetworks=useMemo(()=>ipv4Networks.filter(n=>n.router_id===formData.router_id&&n.usage_type===usage),[ipv4Networks,formData.router_id,usage]);
  const selectedNap=napBoxes.find(n=>n.id===formData.nap_box_id); const occupied=new Set(Object.keys(selectedNap?.assigned_ports||{}).map(Number));
  const availableNapPorts=Array.from({length:selectedNap?.ports||0},(_,i)=>i+1).filter(p=>!occupied.has(p)||Number(formData.nap_port)===p);
  const routerReady=!!formData.router_id, technologyReady=routerReady&&!!formData.technology, planReady=technologyReady&&!!formData.plan_id, connectionReady=planReady&&!!formData.connection_type;
  const accessReady=formData.connection_type==="PPPoE"?connectionReady&&!!formData.pppoe_user.trim():connectionReady&&!!formData.ipv4_network_id&&!!formData.ip_address;
  const zoneReady=accessReady&&!!formData.zone_id;
  const technicalReady=formData.technology==="fiber"?zoneReady&&!!formData.nap_box_id&&!!formData.nap_port:zoneReady&&!!formData.monitoring_equipment_id;
  const canSubmit=routerReady&&technologyReady&&planReady&&connectionReady&&accessReady&&zoneReady&&technicalReady;
  const steps=[{label:"Router",ready:routerReady},{label:"Tecnología",ready:technologyReady},{label:"Plan",ready:planReady},{label:"Conexión",ready:connectionReady},{label:"Acceso",ready:accessReady},{label:"Zona",ready:technicalReady}];

  useEffect(()=>{if(!formData.ipv4_network_id||formData.connection_type==="PPPoE"){setAvailableAddresses([]);return;}let active=true;setLoadingAddresses(true);axios.get(`${api}/ipv4-networks/${formData.ipv4_network_id}/available-addresses`,{params:{exclude_client_id:clientId},headers:{Authorization:`Bearer ${token}`}}).then(r=>{if(active)setAvailableAddresses(r.data.addresses||[])}).catch(()=>{if(active)setAvailableAddresses([])}).finally(()=>{if(active)setLoadingAddresses(false)});return()=>{active=false};},[api,clientId,formData.connection_type,formData.ipv4_network_id,token]);

  const routerChange=e=>setFormData(p=>({...p,router_id:e.target.value,technology:"",plan_id:"",connection_type:"IP Estática",...resetTechnical}));
  const technologyChange=e=>setFormData(p=>({...p,technology:e.target.value,plan_id:"",connection_type:"IP Estática",...resetTechnical}));
  const planChange=e=>setFormData(p=>({...p,plan_id:e.target.value,connection_type:"IP Estática",...resetTechnical}));
  const connectionChange=e=>setFormData(p=>({...p,connection_type:e.target.value,...resetTechnical}));
  const networkChange=e=>setFormData(p=>({...p,ipv4_network_id:e.target.value,ip_address:"",zone_id:"",nap_box_id:"",nap_port:"",onu_sn:"",optical_power_dbm:"",monitoring_equipment_id:"",antenna_type:"",management_ip:""}));
  const ipChange=e=>setFormData(p=>({...p,ip_address:e.target.value,zone_id:"",nap_box_id:"",nap_port:"",onu_sn:"",optical_power_dbm:"",monitoring_equipment_id:"",antenna_type:"",management_ip:""}));
  const zoneChange=e=>setFormData(p=>({...p,zone_id:e.target.value,nap_box_id:"",nap_port:"",onu_sn:"",optical_power_dbm:"",monitoring_equipment_id:"",antenna_type:"",management_ip:""}));

  const submit=async(e)=>{e.preventDefault();setSaving(true);setError("");try{if(!canSubmit)throw new Error("Completa los campos obligatorios en orden.");const selectedPlan=plans.find(p=>String(p.id)===String(formData.plan_id));if(!selectedPlan||planTechnology(selectedPlan.type)!==formData.technology)throw new Error("El plan seleccionado no corresponde a la tecnología elegida.");const payload={plan_id:formData.plan_id,router_id:formData.router_id,connection_type:formData.connection_type,ipv4_network_id:formData.ipv4_network_id||null,ip_address:formData.ip_address||null,pppoe_user:formData.pppoe_user||null,pppoe_password:formData.pppoe_password||null,technology:formData.technology,zone_id:formData.zone_id||null,nap_box_id:formData.technology==="fiber"?formData.nap_box_id||null:null,nap_port:formData.technology==="fiber"&&formData.nap_port?parseInt(formData.nap_port,10):null,onu_sn:formData.technology==="fiber"?formData.onu_sn||null:null,optical_power_dbm:formData.technology==="fiber"&&formData.optical_power_dbm!==""?parseFloat(formData.optical_power_dbm):null,monitoring_equipment_id:formData.technology==="wireless"?formData.monitoring_equipment_id||null:null,antenna_type:formData.technology==="wireless"?formData.antenna_type||null:null,management_ip:formData.technology==="wireless"?formData.management_ip||null:null};const headers={Authorization:`Bearer ${token}`};if(editingPrimary)await axios.patch(`${api}/clients/${clientId}/service`,payload,{headers});else if(service)await axios.patch(`${api}/clients/${clientId}/services/${service.service_id}`,payload,{headers});else await axios.post(`${api}/clients/${clientId}/services`,payload,{headers});onSaved?.({type:editingPrimary||service?"edit":"create",service:{...(service||{}),...formData}});onClose?.();}catch(err){setError(err.response?.data?.detail||err.message||"Error al guardar el servicio.");}finally{setSaving(false)}};

  if(loading)return <div className="service-wizard-overlay fixed inset-0 z-[80] flex items-center justify-center p-4"><div className="service-wizard-modal rounded-2xl p-8 text-center"><Loader className="mx-auto h-6 w-6 animate-spin"/></div></div>;
  return <div className="service-wizard-overlay fixed inset-0 z-[80] flex items-center justify-center p-4" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)onClose?.()}}>
    <div className="service-wizard-modal service-wizard-modal--compact flex max-h-[88vh] w-full max-w-5xl flex-col overflow-hidden rounded-2xl" onMouseDown={e=>e.stopPropagation()}>
      <header className="service-wizard-header shrink-0 border-b px-5 py-3.5"><div className="flex items-center justify-between"><div><h2 className="service-wizard-title text-xl font-black">{editingPrimary?"Editar servicio principal":service?"Editar servicio":"Nuevo servicio"}</h2></div><button type="button" onClick={onClose} disabled={saving} className="service-wizard-close rounded-lg p-2"><X className="h-5 w-5"/></button></div></header>
      <div className="service-wizard-stepper shrink-0 px-5 py-2.5"><div className="mx-auto flex max-w-3xl items-center gap-2">{steps.map((s,i)=><React.Fragment key={s.label}><div className={`service-wizard-step flex items-center gap-1.5 ${s.ready?"is-ready":""}`}><span className="service-wizard-step-number">{s.ready?<CheckCircle2 className="h-3.5 w-3.5"/>:i+1}</span><span className="service-wizard-step-label text-xs font-bold">{s.label}</span></div>{i<steps.length-1&&<span className={`service-wizard-step-line ${s.ready?"is-ready":""}`}/>}</React.Fragment>)}</div></div>
      <div className="overflow-y-auto p-4">{error&&<div className="service-wizard-error mb-3 flex gap-2 rounded-xl p-3"><AlertCircle className="h-5 w-5"/><p className="text-sm">{typeof error==="string"?error:error?.message}</p></div>}
        <form id="client-service-form" onSubmit={submit} className="grid grid-cols-1 gap-4 lg:grid-cols-2">
          <section className="service-wizard-card service-wizard-column p-4"><h3 className="service-wizard-card-title mb-4 text-base font-extrabold">Internet y Router</h3><div className="space-y-3">
            <Field label="Router *"><select value={formData.router_id} onChange={routerChange} className={inputClass} required><option value="">Selecciona un router</option>{routers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field>
            <Field label="Tecnología *"><select value={formData.technology} onChange={technologyChange} disabled={!routerReady} className={inputClass} required><option value="">Tecnología</option><option value="fiber">Fibra óptica</option><option value="wireless">Inalámbrico</option></select></Field>
            <Field label="Plan de internet *"><select value={formData.plan_id} onChange={planChange} disabled={!technologyReady} className={inputClass} required><option value="">Plan de internet</option>{compatiblePlans.map(p=><option key={p.id} value={p.id}>{p.name} — S/. {Number(p.price||0).toFixed(2)}</option>)}</select></Field>
            <Field label="Tipo de conexión *"><select value={formData.connection_type} onChange={connectionChange} disabled={!planReady} className={inputClass}><option value="IP Estática">IP estática</option><option value="PPPoE">PPPoE</option><option value="DHCP">DHCP</option></select></Field>
            {formData.connection_type==="PPPoE"?<><Field label="Usuario PPPoE *"><input value={formData.pppoe_user} onChange={e=>setFormData(p=>({...p,pppoe_user:e.target.value,zone_id:"",nap_box_id:"",nap_port:""}))} disabled={!connectionReady} placeholder="usuario_pppoe" className={inputClass}/></Field><Field label="Clave PPPoE"><input type="password" value={formData.pppoe_password} onChange={e=>setFormData(p=>({...p,pppoe_password:e.target.value}))} disabled={!connectionReady||!formData.pppoe_user.trim()} placeholder="Clave PPPoE" className={inputClass}/></Field></>:<><Field label="Red IPv4 *"><select value={formData.ipv4_network_id} onChange={networkChange} disabled={!connectionReady} className={inputClass}><option value="">Selecciona una red</option>{compatibleNetworks.map(n=><option key={n.id} value={n.id}>{n.name} — {n.cidr}</option>)}</select></Field><Field label="IP disponible *"><select value={formData.ip_address} onChange={ipChange} disabled={!formData.ipv4_network_id||loadingAddresses} className={inputClass}><option value="">{loadingAddresses?"Consultando…":"Selecciona una IP"}</option>{formData.ip_address&&!availableAddresses.includes(formData.ip_address)&&<option value={formData.ip_address}>{formData.ip_address}</option>}{availableAddresses.map(a=><option key={a} value={a}>{a}</option>)}</select></Field></>}
          </div></section>
          <section className="service-wizard-card service-wizard-column p-4"><h3 className="service-wizard-card-title mb-4 text-base font-extrabold">Instalación y datos técnicos</h3><div className="space-y-3">
            <Field label="Zona *"><select value={formData.zone_id} onChange={zoneChange} disabled={!accessReady} className={inputClass}><option value="">Selecciona una zona</option>{zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></Field>
            {formData.technology==="fiber"?<><Field label="Caja NAP *"><select value={formData.nap_box_id} disabled={!formData.zone_id} onChange={e=>setFormData(p=>({...p,nap_box_id:e.target.value,nap_port:"",onu_sn:"",optical_power_dbm:""}))} className={inputClass}><option value="">Selecciona una caja NAP</option>{napBoxes.filter(n=>n.zone_id===formData.zone_id).map(n=><option key={n.id} value={n.id}>{n.display_name||n.name} ({n.ports} puertos)</option>)}</select></Field><Field label="Puerto NAP *"><select value={formData.nap_port} disabled={!formData.nap_box_id} onChange={e=>setFormData(p=>({...p,nap_port:e.target.value,onu_sn:"",optical_power_dbm:""}))} className={inputClass}><option value="">Selecciona un puerto</option>{availableNapPorts.map(p=><option key={p} value={p}>Puerto {p}</option>)}</select></Field><Field label="Serie ONU (opcional)"><input value={formData.onu_sn} onChange={e=>setFormData(p=>({...p,onu_sn:e.target.value}))} disabled={!formData.nap_port} placeholder="SN / MAC de la ONU" className={inputClass}/></Field><Field label="Potencia de la ONU (dBm, opcional)"><input type="number" step="0.1" min="-40" max="0" value={formData.optical_power_dbm} onChange={e=>setFormData(p=>({...p,optical_power_dbm:e.target.value===""?"":String(-Math.abs(Number(e.target.value)))}))} disabled={!formData.nap_port} placeholder="-19.5" className={inputClass}/></Field></>:formData.technology==="wireless"?<><Field label="Conectado a *"><select value={formData.monitoring_equipment_id} disabled={!formData.zone_id} onChange={e=>setFormData(p=>({...p,monitoring_equipment_id:e.target.value,antenna_type:"",management_ip:""}))} className={inputClass}><option value="">Selecciona el equipo</option>{monitoringEquipment.map(eq=><option key={eq.id} value={eq.id}>{eq.name}{eq.management_ip?` — ${eq.management_ip}`:""}</option>)}</select></Field><Field label="Tipo de antena (opcional)"><input value={formData.antenna_type} onChange={e=>setFormData(p=>({...p,antenna_type:e.target.value}))} disabled={!formData.monitoring_equipment_id} className={inputClass}/></Field><Field label="IP de administración (opcional)"><input value={formData.management_ip} onChange={e=>setFormData(p=>({...p,management_ip:e.target.value}))} disabled={!formData.monitoring_equipment_id} className={inputClass}/></Field></>:null}
          </div></section>
        </form>
      </div>
      <footer className="service-wizard-footer flex shrink-0 justify-end gap-2 border-t px-5 py-3"><button type="button" onClick={onClose} disabled={saving} className="service-wizard-close rounded-xl border px-4 py-2 text-sm">Cancelar</button><button type="submit" form="client-service-form" disabled={saving||!canSubmit} className="service-wizard-save inline-flex items-center gap-2 rounded-xl bg-cyan-600 px-5 py-2 text-sm font-bold text-white">{saving?<Loader className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}{saving?"Guardando…":editingPrimary||service?"Guardar cambios":"Registrar servicio"}</button></footer>
    </div></div>;
}

export default function ClientServiceEditor({clientId,api,token,onSave,onSaveSuccess}){
  const [services,setServices]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[modalService,setModalService]=useState(undefined);
  const loadServices=async()=>{setLoading(true);setError("");try{const r=await axios.get(`${api}/clients/${clientId}/services`,{headers:{Authorization:`Bearer ${token}`}});setServices(r.data||[])}catch(err){setError(err.response?.data?.detail||"No se pudieron cargar los servicios del cliente.")}finally{setLoading(false)}};
  useEffect(()=>{loadServices()},[api,clientId,token]);
  const afterSaved=(event={})=>{setModalService(undefined);loadServices();onSave?.();onSaveSuccess?.(event)};
  const deleteService=async(s)=>{if(s.is_primary)return;if(!window.confirm("¿Eliminar este servicio adicional? Esta acción es permanente."))return;try{const headers={Authorization:`Bearer ${token}`};const url=`${api}/clients/${clientId}/services/${s.service_id}`;let result;try{result=await axios.delete(url,{headers})}catch(err){const d=err.response?.data?.detail;if(err.response?.status!==409||d?.code!=="PENDING_INVOICES")throw err;if(!window.confirm(`El servicio tiene ${Number(d.count||0)} factura(s) pendiente(s) por S/. ${Number(d.total||0).toFixed(2)}. ¿Eliminar también esas facturas pendientes?`))return;result=await axios.delete(`${url}?confirm_delete_invoices=true`,{headers})}await loadServices();onSave?.();onSaveSuccess?.({type:"delete",service:s,result:result?.data||{}})}catch(err){setError(err.response?.data?.detail?.message||err.response?.data?.detail||"No se pudo eliminar el servicio.")}};
  if(loading)return <div className="p-10 text-center"><Loader className="mx-auto h-5 w-5 animate-spin"/></div>;
  return <div className="client-services-panel space-y-4">{error&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-300">{error}</div>}<section className="client-services-card overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/35"><div className="client-services-heading flex items-center justify-between border-b border-slate-800 px-5 py-4"><div><h3 className="text-base font-bold text-white">Servicios de Internet</h3></div><button type="button" onClick={()=>setModalService(null)} className="inline-flex items-center gap-2 rounded-xl bg-cyan-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4"/> Nuevo servicio</button></div><div className="overflow-x-auto"><table className="client-services-table min-w-full text-left text-sm"><thead className="bg-slate-950/70 text-xs text-slate-500"><tr><th className="px-4 py-3">Servicio</th><th>Plan</th><th>IP</th><th>Router</th><th>Tecnología</th><th>Señal ONU</th><th>Estado</th><th className="px-4 text-right">Acciones</th></tr></thead><tbody>{services.length===0?<tr><td colSpan="8" className="p-10 text-center text-slate-500">No hay servicios registrados.</td></tr>:services.map((s,i)=><tr key={s.service_id||i} className="border-t border-slate-800"><td className="px-4 py-3 font-semibold text-slate-200">{s.is_primary?"Principal":`Servicio ${i}`}</td><td>{s.plan_name||"Sin plan"}<div className="text-xs text-slate-500">S/. {Number(s.plan_price||0).toFixed(2)}</div></td><td>{s.ip_address||s.pppoe_user||"—"}</td><td>{s.router_name||"—"}</td><td>{s.technology==="wireless"?"Inalámbrico":"Fibra óptica"}</td><td>{s.technology==="fiber"&&s.optical_power_dbm!=null?<span className={`rounded-full px-2 py-1 text-xs ${opticalPowerBadgeClass(s.optical_power_dbm)}`}>{Number(s.optical_power_dbm).toFixed(1)} dBm</span>:"—"}</td><td>{s.status==="active"?"Activo":s.status||"—"}</td><td className="px-4"><div className="flex justify-end gap-1"><button type="button" onClick={()=>setModalService(s)} className="p-2 text-slate-400"><Pencil className="h-4 w-4"/></button>{!s.is_primary&&<button type="button" onClick={()=>deleteService(s)} className="p-2 text-slate-400"><Trash2 className="h-4 w-4"/></button>}</div></td></tr>)}</tbody></table></div></section>{modalService!==undefined&&<ServiceModal clientId={clientId} api={api} token={token} service={modalService} onSaved={afterSaved} onClose={()=>setModalService(undefined)}/>}</div>;
}
