import React, { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { CalendarDays, CheckCircle2, ClipboardList, MapPin, PackageCheck, Phone, RefreshCw, Search, SendToBack, UserRound, XCircle } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "../../../context/AuthContext";
import "./equipment-recovery.css";

const STATUS_LABELS={pending:"Pendiente",contacted:"Contactado",visit_scheduled:"Visita programada",recovered:"Recuperado",not_recovered:"No recuperado"};
const CLOSED=new Set(["recovered","not_recovered"]);
const DISPOSITION_LABELS={available:"Disponible para reutilizar",inspection:"En revisión",damaged:"Averiado",decommissioned:"Baja"};
const itemKey=(item)=>String(item.equipment_id||item.identifier||"");
const equipmentText=(row)=>(row?.equipment?.items||[]).map(i=>[i.type,i.brand_model,i.identifier].filter(Boolean).join(" · ")).join(", ")||"Equipo por verificar en campo";

export default function EquipmentRecovery(){
 const {API,token}=useAuth(); const headers=token?{Authorization:`Bearer ${token}`}:{}, requestConfig={headers,withCredentials:true};
 const [loading,setLoading]=useState(true),[recoveries,setRecoveries]=useState([]),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({status:"pending",assigned_to:"",scheduled_date:"",notes:""});
 const [inventoryReturn,setInventoryReturn]=useState(null),[returnSaving,setReturnSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await axios.get(`${API}/equipment-recoveries`,requestConfig);setRecoveries(Array.isArray(r.data)?r.data:[]);}catch(e){toast.error(e.response?.data?.detail||"No se pudo cargar Recuperación de equipos");}finally{setLoading(false)}};
 useEffect(()=>{load()},[API,token]);
 const filtered=recoveries.filter(r=>{const q=search.trim().toLowerCase();return(!q||[r.client_name,r.dni_ruc,r.phone,r.address,r.assigned_to,equipmentText(r)].join(" ").toLowerCase().includes(q))&&(status==="all"||r.status===status)});
 const counts=useMemo(()=>({pending:recoveries.filter(r=>r.status==="pending").length,contacted:recoveries.filter(r=>r.status==="contacted").length,visit:recoveries.filter(r=>r.status==="visit_scheduled").length,recovered:recoveries.filter(r=>r.status==="recovered").length}),[recoveries]);
 const openCase=(row)=>{setEditing(row);setForm({status:CLOSED.has(row.status)?row.status:row.status||"pending",assigned_to:row.assigned_to||"",scheduled_date:row.scheduled_date||"",notes:row.notes||""})};
 const save=async()=>{if(form.status==="visit_scheduled"&&!form.scheduled_date)return toast.error("Indica la fecha de visita.");setSaving(true);try{const r=await axios.patch(`${API}/equipment-recoveries/${editing.id}`,form,requestConfig);toast.success(r.data?.message||"Seguimiento actualizado");setEditing(r.data.recovery);await load();}catch(e){toast.error(e.response?.data?.detail||"No se pudo actualizar el caso")}finally{setSaving(false)}};
 const resolveItem=async(item,result)=>{const label=result==="recovered"?"recuperado":"no recuperado";if(!window.confirm(`¿Marcar ${item.type||"equipo"} ${item.identifier||""} como ${label}?`))return;try{const r=await axios.patch(`${API}/equipment-recoveries/${editing.id}/equipment/${encodeURIComponent(itemKey(item))}`,{status:result,notes:item.recovery_notes||""},requestConfig);toast.success(r.data?.message||"Equipo actualizado");setEditing(r.data.recovery);await load();}catch(e){toast.error(e.response?.data?.detail||"No se pudo actualizar el equipo")}};
 const updateItemNote=(key,value)=>setEditing(prev=>({...prev,equipment:{...prev.equipment,items:(prev.equipment?.items||[]).map(i=>itemKey(i)===key?{...i,recovery_notes:value}:i)}}));
 const openInventoryReturn=async(item)=>{try{const r=await axios.get(`${API}/equipment-recoveries/${editing.id}/equipment/${encodeURIComponent(itemKey(item))}/inventory-matches`,requestConfig);const matches=r.data?.matches||[];setInventoryReturn({item,matches,disposition:"available",inventory_item_id:matches.length===1?matches[0].id:"",create_new:matches.length===0,location:"Almacén Central",notes:""});}catch(e){toast.error(e.response?.data?.detail||"No se pudo consultar Almacén")}};
 const saveInventoryReturn=async()=>{if(!inventoryReturn)return;setReturnSaving(true);try{const payload={disposition:inventoryReturn.disposition,inventory_item_id:inventoryReturn.inventory_item_id||"",create_new:inventoryReturn.create_new,location:inventoryReturn.location||"Almacén Central",notes:inventoryReturn.notes||""};const r=await axios.post(`${API}/equipment-recoveries/${editing.id}/equipment/${encodeURIComponent(itemKey(inventoryReturn.item))}/inventory-return`,payload,requestConfig);toast.success(r.data?.message||"Equipo registrado en Almacén");setEditing(r.data.recovery);setInventoryReturn(null);await load();}catch(e){toast.error(e.response?.data?.detail||"No se pudo registrar el retorno a Almacén")}finally{setReturnSaving(false)}};
 return <div className="equipment-recovery-page space-y-4 animate-in fade-in duration-200">
  <section className="recovery-hero rounded-2xl border p-4 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex items-start gap-3"><span className="recovery-icon flex h-10 w-10 items-center justify-center rounded-xl"><PackageCheck className="h-5 w-5"/></span><div><h2 className="text-2xl font-black">Recuperación de equipos</h2><p className="mt-1 text-xs">Control de responsables, contactos, visitas, recuperación y retorno seguro a Almacén.</p></div></div><button onClick={load} className="recovery-secondary inline-flex items-center justify-center gap-2 rounded-xl border px-3 py-2 text-xs font-bold"><RefreshCw className="h-4 w-4"/> Actualizar</button></div>
   <div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4"><div className="recovery-stat rounded-xl border p-3"><b>{counts.pending}</b><span>Pendientes</span></div><div className="recovery-stat rounded-xl border p-3"><b>{counts.contacted}</b><span>Contactados</span></div><div className="recovery-stat rounded-xl border p-3"><b>{counts.visit}</b><span>Visitas</span></div><div className="recovery-stat rounded-xl border p-3"><b>{counts.recovered}</b><span>Recuperados</span></div></div></section>
  <section className="recovery-card overflow-hidden rounded-2xl border shadow-sm"><div className="flex flex-col gap-3 border-b p-4 md:flex-row md:items-center md:justify-between"><div><h3 className="font-black">Seguimiento de recuperaciones</h3><p className="text-xs opacity-70">Pendiente → Contactado → Visita programada → Recuperado / No recuperado.</p></div><div className="flex gap-2"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 opacity-50"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente, equipo..." className="recovery-input rounded-xl border py-2 pl-9 pr-3 text-xs"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="recovery-input rounded-xl border px-3 py-2 text-xs"><option value="all">Todos los estados</option>{Object.entries(STATUS_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead><tr><th>Cliente</th><th>Contacto / dirección</th><th>Equipo</th><th>Origen</th><th>Estado</th><th>Responsable / visita</th><th>Acción</th></tr></thead><tbody>{loading?<tr><td colSpan="7" className="p-8 text-center">Cargando...</td></tr>:filtered.length?filtered.map(r=><tr key={r.id}><td><b>{r.client_name}</b><div>DNI/RUC: {r.dni_ruc||"—"}</div></td><td><div><Phone className="mr-1 inline h-3 w-3"/>{r.phone||"—"}</div><div><MapPin className="mr-1 inline h-3 w-3"/>{r.address||"—"}</div></td><td><b>{equipmentText(r)}</b></td><td>{r.source_status==="retired"?"Retirado":"Suspendido"}</td><td><span className={`recovery-status recovery-status-${r.status}`}>{STATUS_LABELS[r.status]||r.status}</span></td><td>{r.assigned_to||"Sin asignar"}<div>{r.scheduled_date?`Visita: ${r.scheduled_date}`:"Sin visita"}</div></td><td><button onClick={()=>openCase(r)} className="recovery-secondary rounded-lg border px-3 py-2 font-bold"><ClipboardList className="mr-1 inline h-3.5 w-3.5"/> {CLOSED.has(r.status)?"Ver detalle":"Gestionar"}</button></td></tr>):<tr><td colSpan="7" className="p-8 text-center opacity-60">No hay casos de recuperación con este filtro.</td></tr>}</tbody></table></div></section>
  <div className="recovery-note rounded-xl border px-4 py-3 text-xs"><PackageCheck className="mr-1 inline h-4 w-4"/>Etapa 4 habilita el retorno a <b>Almacén solo mediante coincidencia exacta por Serial/MAC o creación controlada de un registro nuevo.</b></div>
  {editing&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/45 p-4"><div className="recovery-modal max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-2xl border p-5 shadow-2xl"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><PackageCheck className="h-5 w-5 text-cyan-500"/><h3 className="text-lg font-black">Caso de recuperación</h3><span className={`recovery-status recovery-status-${editing.status}`}>{STATUS_LABELS[editing.status]}</span></div><p className="mt-1 text-xs opacity-70">{editing.client_name} · {editing.phone||"Sin teléfono"} · {editing.address||"Sin dirección"}</p></div><button onClick={()=>setEditing(null)} className="recovery-secondary rounded-lg border px-3 py-2 text-xs">Cerrar</button></div>
   {!CLOSED.has(editing.status)&&<div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-3"><label className="text-xs font-bold"><UserRound className="mr-1 inline h-3.5 w-3.5"/>Responsable<input value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})} className="recovery-input mt-1 w-full rounded-xl border p-2.5" placeholder="Técnico / responsable"/></label><label className="text-xs font-bold">Estado<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="recovery-input mt-1 w-full rounded-xl border p-2.5"><option value="pending">Pendiente</option><option value="contacted">Contactado</option><option value="visit_scheduled">Visita programada</option></select></label><label className="text-xs font-bold"><CalendarDays className="mr-1 inline h-3.5 w-3.5"/>Fecha de visita<input type="date" value={form.scheduled_date} onChange={e=>setForm({...form,scheduled_date:e.target.value})} className="recovery-input mt-1 w-full rounded-xl border p-2.5"/></label><label className="text-xs font-bold md:col-span-3">Observaciones<textarea value={form.notes} maxLength={2000} onChange={e=>setForm({...form,notes:e.target.value})} className="recovery-input mt-1 min-h-20 w-full rounded-xl border p-2.5" placeholder="Contacto, coordinación y resultado de visita..."/></label><div className="md:col-span-3 flex justify-end"><button disabled={saving} onClick={save} className="recovery-primary rounded-xl px-4 py-2 text-xs font-bold disabled:opacity-50">{saving?"Guardando...":"Guardar seguimiento"}</button></div></div>}
   <div className="mt-5"><h4 className="font-black">Equipos del caso</h4><div className="mt-2 space-y-2">{(editing.equipment?.items||[]).map((i,idx)=>{const k=itemKey(i),rawStatus=i.status||"pending",st=CLOSED.has(rawStatus)?rawStatus:"pending";return <div key={k||idx} className="recovery-equipment-row rounded-xl border p-3"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><b>{i.type||"Equipo"}</b>{i.brand_model&&<span> · {i.brand_model}</span>}<div className="text-xs opacity-70">Serial / MAC: {i.identifier||i.serial_mac||"—"}</div>{i.inventory_returned_at&&<div className="mt-1 text-xs font-bold text-emerald-500">Almacén: {DISPOSITION_LABELS[i.inventory_disposition]||i.inventory_disposition} · {i.inventory_item_code||"registrado"}</div>}</div><div className="flex flex-wrap items-center gap-2"><span className={`recovery-status recovery-status-${st}`}>{STATUS_LABELS[st]||"Pendiente"}</span>{st==="recovered"&&!i.inventory_returned_at&&<button onClick={()=>openInventoryReturn(i)} className="recovery-primary rounded-lg px-3 py-2 text-xs font-bold"><SendToBack className="mr-1 inline h-4 w-4"/>Enviar a Almacén</button>}</div></div>{!CLOSED.has(editing.status)&&st==="pending"&&<><input value={i.recovery_notes||""} onChange={e=>updateItemNote(k,e.target.value)} className="recovery-input mt-3 w-full rounded-xl border p-2 text-xs" placeholder="Observación del equipo (opcional)"/><div className="mt-2 flex flex-wrap justify-end gap-2"><button onClick={()=>resolveItem(i,"not_recovered")} className="recovery-danger rounded-lg px-3 py-2 text-xs font-bold"><XCircle className="mr-1 inline h-4 w-4"/>No recuperado</button><button onClick={()=>resolveItem(i,"recovered")} className="recovery-success rounded-lg px-3 py-2 text-xs font-bold"><CheckCircle2 className="mr-1 inline h-4 w-4"/>Recuperado</button></div></>}</div>})}</div></div>
   {(editing.equipment?.history||[]).length>0&&<div className="mt-5"><h4 className="font-black">Historial del caso</h4><div className="mt-2 max-h-40 overflow-y-auto rounded-xl border">{[...(editing.equipment.history||[])].reverse().map((h,i)=><div key={i} className="border-b px-3 py-2 text-xs last:border-b-0"><b>{h.action}</b> · {h.detail}<div className="opacity-60">{h.at} · {h.user}</div></div>)}</div></div>}
  </div></div>}
  {inventoryReturn&&<div className="fixed inset-0 z-[110] flex items-center justify-center bg-black/55 p-4"><div className="recovery-modal w-full max-w-lg rounded-2xl border p-5 shadow-2xl"><div className="flex items-start justify-between"><div><h3 className="text-lg font-black">Retorno a Almacén</h3><p className="mt-1 text-xs opacity-70">{inventoryReturn.item.type||"Equipo"} · {inventoryReturn.item.brand_model||""} · {inventoryReturn.item.identifier||"Sin serial"}</p></div><button onClick={()=>setInventoryReturn(null)} className="recovery-secondary rounded-lg border px-3 py-2 text-xs">Cerrar</button></div><div className="mt-4 space-y-3"><label className="block text-xs font-bold">Destino final<select value={inventoryReturn.disposition} onChange={e=>setInventoryReturn({...inventoryReturn,disposition:e.target.value})} className="recovery-input mt-1 w-full rounded-xl border p-2.5">{Object.entries(DISPOSITION_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{inventoryReturn.matches.length>0?<label className="block text-xs font-bold">Registro exacto de Almacén<select value={inventoryReturn.inventory_item_id} onChange={e=>setInventoryReturn({...inventoryReturn,inventory_item_id:e.target.value,create_new:false})} className="recovery-input mt-1 w-full rounded-xl border p-2.5"><option value="">Selecciona el registro coincidente</option>{inventoryReturn.matches.map(m=><option key={m.id} value={m.id}>{m.item_code} · {m.name} · stock {m.stock}</option>)}</select></label>:<div className="recovery-note rounded-xl border p-3 text-xs">No existe una coincidencia exacta por Serial/MAC. Z-Hub creará un registro nuevo para este equipo recuperado; no se asociará por nombre o modelo.</div>}<label className="block text-xs font-bold">Ubicación<input value={inventoryReturn.location} onChange={e=>setInventoryReturn({...inventoryReturn,location:e.target.value})} className="recovery-input mt-1 w-full rounded-xl border p-2.5"/></label><label className="block text-xs font-bold">Observación<textarea value={inventoryReturn.notes} onChange={e=>setInventoryReturn({...inventoryReturn,notes:e.target.value})} className="recovery-input mt-1 min-h-20 w-full rounded-xl border p-2.5" placeholder="Estado físico, accesorios, revisión necesaria..."/></label><div className="flex justify-end gap-2 pt-2"><button onClick={()=>setInventoryReturn(null)} className="recovery-secondary rounded-xl border px-4 py-2 text-xs font-bold">Cancelar</button><button disabled={returnSaving||(inventoryReturn.matches.length>0&&!inventoryReturn.inventory_item_id)} onClick={saveInventoryReturn} className="recovery-primary rounded-xl px-4 py-2 text-xs font-bold disabled:opacity-50">{returnSaving?"Registrando...":"Registrar en Almacén"}</button></div></div></div></div>}
 </div>
}
